/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ShellIndexRouteImport } from './routes/_shell/index'
import { Route as ShellArchiveRouteImport } from './routes/_shell/archive'
import { Route as ShellRemindersRouteImport } from './routes/_shell/reminders'
import { Route as ShellSearchRouteImport } from './routes/_shell/search'
import { Route as ShellTrashRouteImport } from './routes/_shell/trash'
import { Route as ShellLabelLabelNameRouteImport } from './routes/_shell/label.$labelName'

const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellIndexRoute = ShellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellArchiveRoute = ShellArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => ShellRoute,
} as any)
const ShellRemindersRoute = ShellRemindersRouteImport.update({
  id: '/reminders',
  path: '/reminders',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSearchRoute = ShellSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => ShellRoute,
} as any)
const ShellTrashRoute = ShellTrashRouteImport.update({
  id: '/trash',
  path: '/trash',
  getParentRoute: () => ShellRoute,
} as any)
const ShellLabelLabelNameRoute = ShellLabelLabelNameRouteImport.update({
  id: '/label/$labelName',
  path: '/label/$labelName',
  getParentRoute: () => ShellRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ShellIndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/archive': typeof ShellArchiveRoute
  '/reminders': typeof ShellRemindersRoute
  '/search': typeof ShellSearchRoute
  '/trash': typeof ShellTrashRoute
  '/label/$labelName': typeof ShellLabelLabelNameRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/archive': typeof ShellArchiveRoute
  '/reminders': typeof ShellRemindersRoute
  '/search': typeof ShellSearchRoute
  '/trash': typeof ShellTrashRoute
  '/': typeof ShellIndexRoute
  '/label/$labelName': typeof ShellLabelLabelNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_shell': typeof ShellRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_shell/archive': typeof ShellArchiveRoute
  '/_shell/reminders': typeof ShellRemindersRoute
  '/_shell/search': typeof ShellSearchRoute
  '/_shell/trash': typeof ShellTrashRoute
  '/_shell/': typeof ShellIndexRoute
  '/_shell/label/$labelName': typeof ShellLabelLabelNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/reset-password'
    | '/archive'
    | '/reminders'
    | '/search'
    | '/trash'
    | '/label/$labelName'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/reset-password'
    | '/archive'
    | '/reminders'
    | '/search'
    | '/trash'
    | '/'
    | '/label/$labelName'
  id:
    | '__root__'
    | '/_shell'
    | '/login'
    | '/reset-password'
    | '/_shell/archive'
    | '/_shell/reminders'
    | '/_shell/search'
    | '/_shell/trash'
    | '/_shell/'
    | '/_shell/label/$labelName'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ShellRoute: typeof ShellRouteWithChildren
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/': {
      id: '/_shell/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ShellIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/archive': {
      id: '/_shell/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof ShellArchiveRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/reminders': {
      id: '/_shell/reminders'
      path: '/reminders'
      fullPath: '/reminders'
      preLoaderRoute: typeof ShellRemindersRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/search': {
      id: '/_shell/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof ShellSearchRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/trash': {
      id: '/_shell/trash'
      path: '/trash'
      fullPath: '/trash'
      preLoaderRoute: typeof ShellTrashRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/label/$labelName': {
      id: '/_shell/label/$labelName'
      path: '/label/$labelName'
      fullPath: '/label/$labelName'
      preLoaderRoute: typeof ShellLabelLabelNameRouteImport
      parentRoute: typeof ShellRoute
    }
  }
}

interface ShellRouteChildren {
  ShellArchiveRoute: typeof ShellArchiveRoute
  ShellRemindersRoute: typeof ShellRemindersRoute
  ShellSearchRoute: typeof ShellSearchRoute
  ShellTrashRoute: typeof ShellTrashRoute
  ShellIndexRoute: typeof ShellIndexRoute
  ShellLabelLabelNameRoute: typeof ShellLabelLabelNameRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellArchiveRoute: ShellArchiveRoute,
  ShellRemindersRoute: ShellRemindersRoute,
  ShellSearchRoute: ShellSearchRoute,
  ShellTrashRoute: ShellTrashRoute,
  ShellIndexRoute: ShellIndexRoute,
  ShellLabelLabelNameRoute: ShellLabelLabelNameRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ShellRoute: ShellRouteWithChildren,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
