/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ShellIndexRouteImport } from './routes/_shell/index'
import { Route as ShellArchiveRouteImport } from './routes/_shell/archive'
import { Route as ShellRemindersRouteImport } from './routes/_shell/reminders'
import { Route as ShellSearchRouteImport } from './routes/_shell/search'
import { Route as ShellShareRouteImport } from './routes/_shell/share'
import { Route as ShellTemplatesRouteImport } from './routes/_shell/templates'
import { Route as ShellTrashRouteImport } from './routes/_shell/trash'
import { Route as OauthConsentRouteImport } from './routes/oauth.consent'
import { Route as STokenRouteImport } from './routes/s.$token'
import { Route as ShellLabelSplatRouteImport } from './routes/_shell/label.$'

const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellIndexRoute = ShellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellArchiveRoute = ShellArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => ShellRoute,
} as any)
const ShellRemindersRoute = ShellRemindersRouteImport.update({
  id: '/reminders',
  path: '/reminders',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSearchRoute = ShellSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => ShellRoute,
} as any)
const ShellShareRoute = ShellShareRouteImport.update({
  id: '/share',
  path: '/share',
  getParentRoute: () => ShellRoute,
} as any)
const ShellTemplatesRoute = ShellTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => ShellRoute,
} as any)
const ShellTrashRoute = ShellTrashRouteImport.update({
  id: '/trash',
  path: '/trash',
  getParentRoute: () => ShellRoute,
} as any)
const OauthConsentRoute = OauthConsentRouteImport.update({
  id: '/oauth/consent',
  path: '/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const STokenRoute = STokenRouteImport.update({
  id: '/s/$token',
  path: '/s/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellLabelSplatRoute = ShellLabelSplatRouteImport.update({
  id: '/label/$',
  path: '/label/$',
  getParentRoute: () => ShellRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ShellIndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/archive': typeof ShellArchiveRoute
  '/reminders': typeof ShellRemindersRoute
  '/search': typeof ShellSearchRoute
  '/share': typeof ShellShareRoute
  '/templates': typeof ShellTemplatesRoute
  '/trash': typeof ShellTrashRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/s/$token': typeof STokenRoute
  '/label/$': typeof ShellLabelSplatRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/archive': typeof ShellArchiveRoute
  '/reminders': typeof ShellRemindersRoute
  '/search': typeof ShellSearchRoute
  '/share': typeof ShellShareRoute
  '/templates': typeof ShellTemplatesRoute
  '/trash': typeof ShellTrashRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/s/$token': typeof STokenRoute
  '/': typeof ShellIndexRoute
  '/label/$': typeof ShellLabelSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_shell': typeof ShellRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_shell/archive': typeof ShellArchiveRoute
  '/_shell/reminders': typeof ShellRemindersRoute
  '/_shell/search': typeof ShellSearchRoute
  '/_shell/share': typeof ShellShareRoute
  '/_shell/templates': typeof ShellTemplatesRoute
  '/_shell/trash': typeof ShellTrashRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/s/$token': typeof STokenRoute
  '/_shell/': typeof ShellIndexRoute
  '/_shell/label/$': typeof ShellLabelSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/reset-password'
    | '/archive'
    | '/reminders'
    | '/search'
    | '/share'
    | '/templates'
    | '/trash'
    | '/oauth/consent'
    | '/s/$token'
    | '/label/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/reset-password'
    | '/archive'
    | '/reminders'
    | '/search'
    | '/share'
    | '/templates'
    | '/trash'
    | '/oauth/consent'
    | '/s/$token'
    | '/'
    | '/label/$'
  id:
    | '__root__'
    | '/_shell'
    | '/login'
    | '/reset-password'
    | '/_shell/archive'
    | '/_shell/reminders'
    | '/_shell/search'
    | '/_shell/share'
    | '/_shell/templates'
    | '/_shell/trash'
    | '/oauth/consent'
    | '/s/$token'
    | '/_shell/'
    | '/_shell/label/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ShellRoute: typeof ShellRouteWithChildren
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  OauthConsentRoute: typeof OauthConsentRoute
  STokenRoute: typeof STokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/': {
      id: '/_shell/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ShellIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/archive': {
      id: '/_shell/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof ShellArchiveRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/reminders': {
      id: '/_shell/reminders'
      path: '/reminders'
      fullPath: '/reminders'
      preLoaderRoute: typeof ShellRemindersRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/search': {
      id: '/_shell/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof ShellSearchRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/share': {
      id: '/_shell/share'
      path: '/share'
      fullPath: '/share'
      preLoaderRoute: typeof ShellShareRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/templates': {
      id: '/_shell/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof ShellTemplatesRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/trash': {
      id: '/_shell/trash'
      path: '/trash'
      fullPath: '/trash'
      preLoaderRoute: typeof ShellTrashRouteImport
      parentRoute: typeof ShellRoute
    }
    '/oauth/consent': {
      id: '/oauth/consent'
      path: '/oauth/consent'
      fullPath: '/oauth/consent'
      preLoaderRoute: typeof OauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$token': {
      id: '/s/$token'
      path: '/s/$token'
      fullPath: '/s/$token'
      preLoaderRoute: typeof STokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/label/$': {
      id: '/_shell/label/$'
      path: '/label/$'
      fullPath: '/label/$'
      preLoaderRoute: typeof ShellLabelSplatRouteImport
      parentRoute: typeof ShellRoute
    }
  }
}

interface ShellRouteChildren {
  ShellArchiveRoute: typeof ShellArchiveRoute
  ShellRemindersRoute: typeof ShellRemindersRoute
  ShellSearchRoute: typeof ShellSearchRoute
  ShellShareRoute: typeof ShellShareRoute
  ShellTemplatesRoute: typeof ShellTemplatesRoute
  ShellTrashRoute: typeof ShellTrashRoute
  ShellIndexRoute: typeof ShellIndexRoute
  ShellLabelSplatRoute: typeof ShellLabelSplatRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellArchiveRoute: ShellArchiveRoute,
  ShellRemindersRoute: ShellRemindersRoute,
  ShellSearchRoute: ShellSearchRoute,
  ShellShareRoute: ShellShareRoute,
  ShellTemplatesRoute: ShellTemplatesRoute,
  ShellTrashRoute: ShellTrashRoute,
  ShellIndexRoute: ShellIndexRoute,
  ShellLabelSplatRoute: ShellLabelSplatRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ShellRoute: ShellRouteWithChildren,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  OauthConsentRoute: OauthConsentRoute,
  STokenRoute: STokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
